### ISSUE TITLE
Setting the SignalR Service to Serverless

### ISSUE THREAD

**Issue by humblegar** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#11]
I received the following error in the Cloud Shell:

"The resource is not on an infrastructure that supports Network ACL. Network ACL is still in preview. You can try to create a new resource or wait until we migrate your existing resource."

By manually setting the SingalR Service to "Serverless" in the portal I was able to continue the exercise.

**Comment by diberry** [comment]
The sample repo has been refreshed. Please try again.
