### ISSUE TITLE
Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by ZZ-cat33** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#15]
I got "Value cannot be null. (Parameter 'provider')" , when enter F5. I tried to delete the Functions/Microsoft.Azure.Functions.ExtensionBundle and AppData\Local\Temp\7ff6f096-c21f-479c-b708-8276899997b8\ folder as mentioned below. But no luck. 

https://github.com/Azure/azure-functions-core-tools/issues/1924
https://github.com/Azure/azure-functions-core-tools/issues/1995

**Comment by diberry** [comment]
The source code has been updated, please try again.
