### ISSUE TITLE
Example not working with newer versions of Azure Functions

### ISSUE THREAD

**Issue by diabhoil** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#27]
I followed all steps from the learning modules and deployed the function to azure. It seems like new function apps wont work with the existing version of the hosts.json. In the overview area of the functions app I got this error:

> Referenced bundle Microsoft.Azure.Functions.ExtensionBundle of version 1.8.1 does not meet the required minimum version of 2.6.1. Update your extension bundle reference in host.json to reference 2.6.1 or later.

I had to change the hosts.json to:
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```
After redeploying it started to work.

**Comment by diberry** [comment]
The sample code has been refreshed. Thanks for reporting this.
