### ISSUE TITLE
Stock Price doesn't appear in application

### ISSUE THREAD

**Issue by KeoabetsweMorake** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#3]
Utils.ts:183 [2019-07-08T09:22:20.041Z] Warning: Error from HTTP request. 0: .
ConsoleLogger.log @ Utils.ts:183
xhr.onerror @ XhrHttpClient.ts:75
Utils.ts:180 [2019-07-08T09:22:20.041Z] Error: Failed to complete negotiation with the server: Error
ConsoleLogger.log @ Utils.ts:180
(anonymous) @ HttpConnection.ts:247
step @ HttpConnection.ts:2
(anonymous) @ HttpConnection.ts:2
rejected @ HttpConnection.ts:2
Utils.ts:180 [2019-07-08T09:22:20.041Z] Error: Failed to start the connection: Error
ConsoleLogger.log @ Utils.ts:180
(anonymous) @ HttpConnection.ts:215
step @ HttpConnection.ts:2
(anonymous) @ HttpConnection.ts:2
rejected @ HttpConnection.ts:2
:7071/api/negotiate:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
index.html.js:23 Error: Network Error
    at e.exports (spread.js:25)
    at XMLHttpRequest.d.onerror (spread.js:25)
getStocks @ index.html.js:23
:7071/api/getStocks:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
Errors.ts:20 Uncaught (in promise) Error
    at new HttpError (Errors.ts:20)
    at XMLHttpRequest.xhr.onerror (XhrHttpClient.ts:76)
HttpError @ Errors.ts:20
xhr.onerror @ XhrHttpClient.ts:76

**Comment by bayesio** [comment]
I think you might have skipped over a step in the instructions if you are following along with [the learning course](https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/3-exercise-analyze-limitations-of-polling-in-a-web-app#run-the-application). Step 2 says to press **F5** to start debugging the function locally. This should make localhost:7071 no longer say connection refused.

**Comment by AmerjitSingh** [comment]
I have a similar issue, the node process is running...but Vue client cannot access the azure function running locally do to CORS in chrome browser.   The local.settings.json has the server side config but still get 

"Access to XMLHttpRequest at 'http://localhost:7071/api/getStocks' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Have tried playing with CORS settings, making it a wildcard (*) and changed the Vue client to add a CORS Allow header but too no good, any help would be appreciated.

**Comment by AmerjitSingh** [comment]
I understand the problem now, the azure function was running node and not within the context of azure  function local host; run command palette and create an **azure function project** for start or end folder in vscode then run **F5**. Hope this helps someone.

**Comment by nmg196** [comment]
I have the same problem as @AmerjitSingh.
Does anyone know the solution?  I tried to figure out what he meant, went through the steps to create the Azure Function Project but it  didn't resolve the problem.

**Comment by HaiyeWang0717** [comment]
For my situation, first make sure install Azure Functions Core Tools (min. version 2.6.666) and
Azure Functions extension for Visual Studio Code. Then run "npm start", after 8080 port started, then press F5 start debug mode. The stock price will display in browser. Hope this helps.

**Comment by Z-Zhao** [comment]
When press F5 to start debug mode, make sure the VS Code is opening the "Start" folder as the project root folder (instead of "serverless-demo" folder which contains both "start" and "end" folders).

**Comment by kahuy2805** [comment]
for my issue, it's work properly once i run "func start" at start folder after "npm start".

**Comment by hanyzekry** [comment]
1- Run F5
2- make sure that the "version": "2.61" in `/serverless-demo/start/host.json` includes your installed ExtensionBundle version

**Comment by hsafdari** [comment]
I fixed this issue by this steps
1- I didn't install azure-functions-core-tools on my machine, so I downloaded it and install.
2-In host.json file I used bellow command
{
  "version": "2.0",
  "extensionBundle": {
      "id": "Microsoft.Azure.Functions.ExtensionBundle",
      "version": "[3.3.0, 4.0.0)"
  }
}
3- for run function, first should press F5 but "Attach to Node Functions" should be selected
5- in db.js line 16 I replaced below code
 client = new CosmosClient({ endpoint, key: masterKey });

 I spend more than 4 hours to solve this issues. If developers update codes, it would be helpful for us .
 thanks

**Comment by diberry** [comment]
This sample repo has been refreshed. This issue should be resolved now.
