### ISSUE TITLE
lite-server and shrin-wrap.json isuues

### ISSUE THREAD

**Issue by praneeitachi** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#34]
Hi team 
i am facing some issues when i run thenpm start 
in scripts the lite-server is unable to connect. I am attaching the errors below, can you fix this ?
> microsoft-learn-func-signalr-start@1.0.0 start /home/<name>/serverless-demo/start
> lite-server --baseDir="public"

sh: 1: lite-server: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! microsoft-learn-func-signalr-start@1.0.0 start: `lite-server --baseDir="public"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the microsoft-learn-func-signalr-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

--
Can you please update this issue ?

**Comment by diberry** [comment]
Fixed with sample refresh.
