### ISSUE TITLE
mslearn-advocates.azure-functions-and-signalr/start/host.json is outdated

### ISSUE THREAD

**Issue by p-braja** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#40]
The entries in the host.json file needs to be updated,
While running  with the existing entries, it throws error "Referenced bundle Microsoft.Azure.Functions.ExtensionBundle of version 1.8.1 does not meet the required minimum version of 2.6.1. Update your extension bundle reference in host.json to reference 2.6.1 or later." 

If the version of the "extensionBundle" in host.json file is updated to "version": "[2.*, 3.0.0)", then the function app works correctly in local setup
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
} 
![Error-Screenshot](https://user-images.githubusercontent.com/102681771/184208840-f49bfcd6-cdfb-455f-b697-21e5b0ff332c.png)
![Working-Screenshot](https://user-images.githubusercontent.com/102681771/184208848-feb4eb4f-1d54-4ab5-b2f2-03884c2ac4a4.PNG)

**Comment by diberry** [comment]
fixed.
