### ISSUE TITLE
Error setting up database: TypeError: TLSv1 methods disabled

### ISSUE THREAD

**Issue by joblini** [MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr#41]
Getting following error when running `npm install` in exercise https://learn.microsoft.com/en-ca/training/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/3-exercise-analyze-limitations-of-polling-in-a-web-app

Any help would be appreciated !

```
[ ~/serverless-demo/start ]$ npm install

> microsoft-learn-func-signalr-start@1.0.0 postinstall
> npm run setup


> microsoft-learn-func-signalr-start@1.0.0 setup
> node setup.js

Error setting up database: TypeError: TLSv1 methods disabled
    at new SecureContext (node:_tls_common:89:16)
    at Object.createSecureContext (node:_tls_common:114:13)
    at Object.connect (node:_tls_wrap:1623:48)
    at Agent.createConnection (node:https:143:22)
    at Agent.createSocket (node:_http_agent:340:26)
    at Agent.addRequest (node:_http_agent:291:10)
    at new ClientRequest (node:_http_client:311:16)
    at Object.request (node:https:353:10)
    at /home/ingo_jobling/serverless-demo/start/node_modules/@azure/cosmos/lib/src/request/request.js:49:36
    at new Promise (<anonymous>) {
  code: 'ERR_TLS_INVALID_PROTOCOL_METHOD',
  headers: {
    'x-ms-throttle-retry-count': 0,
    'x-ms-throttle-retry-wait-time-ms': 0
  }
}
```

**Comment by JordonMaule** [comment]
I'm getting this same error when trying to complete 'Exercise - Analyze the limitations of a polling-based web app' . Not sure how to solve it.
Subscribing for notification on this issue in case someone replies to you.

**Comment by skayred** [comment]
That can be solved by bumping the Cosmos DB client to the latest version like that in package.json:

`"@azure/cosmos": "^3.17.3",`

That would require small change in the db.js file:

`client = new CosmosClient({ endpoint, key: masterKey });`

**Comment by hsafdari** [comment]
I run below command and use @skayred comment
npm i @azure/cosmos

**Comment by diberry** [comment]
This should be fixed with the samples refresh for this repo.
